spring:
  config:
    import: optional:configserver:http://${CONFIG_URL:localhost}:8888/
  application:
    name: serie-service
  cloud:
    config:
      profile: cp2
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost}:8761/eureka/