spring:
  application:
    name: mail-banking
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
server:
  port: 8002
  servlet:
    context-path: /mailservice/v1



queue:
  mail: queue-mail