version: '3.2'
services:

  rabbitmq-service:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
      
  zipkin-service:
    image: 'openzipkin/zipkin:2'
    container_name: zipkin-service
    ports:
      - '9411:9411'
      
  eureka-service:
    build: eureka
    container_name: eureka-service
    depends_on:
      - zipkin-service
    ports:
      - '8761:8761'
    environment:
      - ZIPKIN_URL=zipkin-service
      
  config-service:
    build: config
    container_name: config-service
    depends_on:
      - eureka-service
    ports:
      - '8888:8888'
    environment:
      - ZIPKIN_URL=zipkin-service
      - EUREKA_URL=eureka-service
      
  gateway-service:
    build: gateway
    container_name: gateway-service
    depends_on:
      - config-service
    ports:
      - '8080:8080'
    environment:
      - ZIPKIN_URL=zipkin-service
      - EUREKA_URL=eureka-service
      - CONFIG_URL=config-service
      
  catalogo-service:
    build: catalogo
    container_name: catalogo-service
    depends_on:
      - gateway-service
    ports:
      - '8097:8097'
    environment:
      - ZIPKIN_URL=zipkin-service
      - RABBIT_URL=rabbitmq-service
      - EUREKA_URL=eureka-service
      - CONFIG_URL=config-service
      
  movie-service:
    build: filmes
    container_name: movie-service
    depends_on:
      - catalogo-service
    ports:
      - '8098:8098'
    environment:
      - ZIPKIN_URL=zipkin-service
      - RABBIT_URL=rabbitmq-service
      - EUREKA_URL=eureka-service
      - CONFIG_URL=config-service
      
  serie-service:
    build: series
    container_name: serie-service
    depends_on:
      - movie-service
    ports:
      - '8099:8099'
    environment:
      - ZIPKIN_URL=zipkin-service
      - RABBIT_URL=rabbitmq-service
      - EUREKA_URL=eureka-service
      - CONFIG_URL=config-service