spring:
  application:
    name: digital-banking
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
server:
  port: 8001
  servlet:
    context-path: /digitalbank/v1/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  packagesToScan: com.digital.bank.api.controller

queue:
  mail: queue-mail

