spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: ${PROFILE:dev}
  application:
    name : catalog-service

resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        failureRateThreshold: 10
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      movie-service:
        maxAttempts: 3
        waitDuration: 100
        retryExceptions:
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$InternalServerError
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitsbreakerevents,health,info
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always