---
- hosts: localhost
  tasks:
  - name: Criar grupo de segurança com HTTPS, HTTP e SSH
    ec2_group:
      name: digitalhouse
      # vpc_id: vpc-0feaf42bebf22baf2
      vpc_id: vpc-0a31ba47a968751e4
      description: sg com as regras
      region: us-west-1
      rules:
      - proto: tcp
        ports:
        - 443
        - 80
        - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: Aceito todo o tráfego nas portas 443, 80 e 22

  - name: Criamos nosso servidor
    ec2:
      region: us-west-1
      group: digitalhouse
      instance_type: t2.micro
      image: ami-0ed05376b59b90e46
      wait: yes
      wait_timeout: 500
      volumes:
        - device_name: /dev/xvda
          volume_type: gp2
          volume_size: 8
      vpc_subnet_id: subnet-070d3b818d23ea3cf
      assign_public_ip: yes
      key_name: pt6aluno45
    register: info
  - name: IP público do nosso servidor
    debug:
      var: info.instances [0] .public_ip
  - name: DNS público de nosso servidor
    debug:
      var: info.instances [0] .public_dns_name