spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: ${PROFILE:dev}
  application:
    name : movie-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher